# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
