# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=1023)),
                ('group', models.CharField(max_length=255)),
                ('plot', models.TextField()),
                ('rating', models.IntegerField()),
                ('youtube_link', models.CharField(max_length=1023)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='comment',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Play'),
        ),
    ]
