# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170725_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='play',
            old_name='youtube_link',
            new_name='youtube',
        ),
        migrations.AddField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(to='web.Genre'),
        ),
    ]
